- clean: ['~', '~/.config']
- link:
    ~/.dotfiles: ''
    ~/.gitconfig: gitconfig
    ~/.vim: vim/
    ~/.vimrc: vimrc
    ~/.zshrc: zshrc
    ~/.zshrc_ssh_agent: zshrc_ssh_agent
- shell:
    - [./core_deps.sh, Installing core dependencies]
    - [git submodule update --init --recursive, Updating submodules]
    - [./brew.sh, Installing and updating homebrew packages]
    - [./ruby-install.sh, Installing latest ruby with rbenv and ruby-build]
    - [./oh-my-zsh-install.sh, Installing oh-my-zsh]
    - ["git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim", Pull in Vundle]
    - [vim -u $HOME/.vim/vimrc/plugins.vim +PluginInstall +qall, Installing Vundle plugins]
    - [./fonts.sh, Installing Powerline patched fonts]
