- clean: ['~', '~/.config']
- link:
    ~/.dotfiles: ''
    ~/.gitconfig: gitconfig
    ~/.vim: vim/
    ~/.vimrc: vimrc
    ~/.zshrc: zshrc
    ~/.zshrc_ssh_agent: zshrc_ssh_agent
- shell:
    - [git submodule update --init --recursive, Updating submodules]
    - [./brew.sh, Installing and updating homebrew packages]
    - [./ruby-install.sh, Installing latest ruby with rbenv and ruby-build]
    - [./oh-my-zsh-install.sh, Installing oh-my-zsh]
    - [vim +PluginInstall +qall, Installing Vundle plugins]
