brew "ack"
brew "ag"
brew "aria2"
brew "cmake"
brew "ctags"
brew "direnv"
brew "findutils"
brew "fzf"
brew "git"
brew "go"
brew "gpg"
brew "htop"
brew "iftop"
brew "jq"
brew "mercurial"
brew "neovim"
brew "nmap"
brew "pigz"
brew "plantuml"
brew "ripgrep"
brew "tcptraceroute"
brew "tig"
brew "tree"
brew "vim"
brew "watch"
brew "wget"
brew "zsh"

# Language related
brew "jenv"
brew "lua-language-server"
brew "pyenv"
brew "rbenv"
brew "ruby-build"
brew "yaml-language-server"
# brew "rust" - use rustup instead
# brew "python" - pyenv
# brew "python3" - pyenv

# Install brew casks
cask_args appdir: "/Applications"
#cask "google-chrome"
#cask "firefox"
cask "alfred"
cask "amethyst"
cask "bettertouchtool"
cask "spotify"
cask "adobe-acrobat-reader"
cask "karabiner-elements"
cask "android-file-transfer"
cask "growlnotify"
cask "iterm2"
cask "vlc"
cask "gpg-suite"
cask "skype"
cask "1Password"
# cask "java"

# Font tap
tap "homebrew/cask-fonts"
cask "font-fira-code"
