brew "cmake"
brew "findutils"
brew "vim", args: ["override-system-vi"]
brew "zsh"
brew "python"
brew "python3"
brew "direnv"
brew "fzf"
brew "go", args: ["cross-compile-common"]
brew "mercurial"
brew "ack"
brew "bzr"
brew "git"
brew "tig"
brew "iftop"
brew "jq"
brew "rbenv"
brew "ruby-build"
brew "htop"
brew "tree"
brew "gpg"
brew "pigz"
brew "wget"
brew "aria2"
brew "watch"
brew "fasd"
brew "nmap"
brew "ag"
brew "tcptraceroute"
brew "ctags"
brew "plantuml"

# Install brew casks
cask_args appdir: "/Applications"
cask "google-chrome"
cask "firefox"
cask "alfred"
cask "amethyst"
cask "bettertouchtool"
cask "spotify"
cask "adobe-acrobat-reader"
cask "karabiner-elements"
cask "android-file-transfer"
cask "growlnotify"
cask "iterm2"
cask "vlc"
cask "gpg-suite"
cask "colloquy"
cask "skype"
cask "java"

# Font tap
tap "caskroom/fonts"
cask "font-fira-code"
